# Week 5. Getting Started with pandas

In [1]:
import pandas as pd
import numpy as np
# from pandas import Series, DataFrame

### Series

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [3]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [4]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='str')

In [5]:
obj2['a']

np.int64(-5)

In [8]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [11]:
a = [1,2,3]

In [12]:
a*2

[1, 2, 3, 1, 2, 3]

In [13]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [14]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b' in obj2
# 'e' not in obj2

True

In [16]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [17]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
# pd.isnull(obj4)
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
obj4.name = 'population'
obj4.index.name = 'state'
df = pd.Series(obj4)
df

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [33]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [34]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
frame.tail(3)
# frame.head(2)

    state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [37]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
index=['one', 'two', 'three', 'four',
'five', 'six'])
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [39]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: str

In [40]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Rows can also be retrieved by position or name with the special loc attribute

In [41]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt'] = 16.5
frame2

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [43]:
frame2['debt'] = np.arange(6.)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

When you are assigning lists or arrays to a column, the value’s length must match the
length of the DataFrame. If you assign a Series, its labels will be realigned exactly to
the DataFrame’s index, inserting missing values in any holes:

In [44]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [45]:
frame2['debt'] = val
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [46]:
frame2['eastern'] = (frame2.state == 'Ohio')
frame2
# New columns cannot be created with the frame2.eastern syntax.

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [47]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

#### Nested dict

In [43]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [44]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [45]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
'Nevada': frame3['Nevada'][:2]}


pd.DataFrame(pdata)

In [46]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [47]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [48]:
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [49]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [50]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [51]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [52]:
index[1:]

Index(['b', 'c'], dtype='object')

Index objects are immutable and thus can’t be modified by the user

In [ ]:
index[1] = 'd' # TypeError

Immutability makes it safer to share Index objects among data structures

In [53]:
labels = pd.Index(np.arange(3))
labels
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

## Essential Functionality

### Reindexing

In [54]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [55]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [56]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [61]:
obj3.reindex(range(6), method = 'bfill') 
# obj3.reindex(range(6))

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [62]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), \
                        index=['a', 'c', 'd'],\
                            columns=['Ohio', 'Texas', 'California'])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [63]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [64]:
# The columns can be reindexed with the columns keyword:
states = ['Texas', 'Utah', 'California']
frame2= frame.reindex(columns=states)

In [65]:
frame2

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping Entries from an Axis

In [66]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [67]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [69]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [68]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [70]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), \
            index=['Ohio', 'Colorado', 'Utah', 'New York'], \
                    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [71]:
data.drop(['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [72]:
data.drop('two', axis=1) # column-wise

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [73]:
data2 = data.drop(['two', 'four'], axis='columns')

In [74]:
data2

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [75]:
data.drop('two', axis = 1, inplace=True) #without returning a new object
data

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### Indexing, Selection, and Filtering

In [76]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [84]:
# obj['b']
# obj[1]
# obj[['b', 'a', 'd']]
# obj[[1, 3]]
# obj[obj < 2]
obj['b':'d'] #endpoint is inclusive
# obj[1:3]
# obj['b':'c'] = 5
# obj

b    1.0
c    2.0
d    3.0
dtype: float64

#### Indexing, Selection, and Filtering the Dataframes

In [85]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), \
            index=['Ohio', 'Colorado', 'Utah', 'New York'], \
                        columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
# data['two']
data[1]
# data[['three', 'one']]
# data[:2]
# data[data['three'] > 5]

# data < 5
# data[data < 5] = 0
# data

KeyError: 1

### Selection with loc and iloc

They enable to select a subset of the rows and columns from a
DataFrame with NumPy-like notation using either axis labels (loc) or integers
(iloc).

In [94]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [96]:
# axis labels (loc) or integers (iloc)
# data.iloc[2, [3, 0, 1]]
# data.iloc[2]
# data.iloc[:,2]
# data.iloc[[1, 2], [3, 0, 1]]
# data.loc[:'Utah', 'two']
# data2 = data.iloc[:, :3]
# data2[data2.three > 5]
# data2

four    11
one      8
two      9
Name: Utah, dtype: int64

### Integer Indexes

In [ ]:
np.arange(3.)
list(range(3))

In [97]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [98]:
ser[-1]

KeyError: -1

In [99]:
# non integer indexing 
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [100]:
ser2[-1]

2.0

### Arithmetic and Data Alignment

In [101]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])
s1
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [102]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [103]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), \
                                index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), \
                                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [104]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [105]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
print(df1)
print(df2)

   A
0  1
1  2
   B
0  3
1  4

In [106]:
df1 - df2

    A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [107]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [108]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [109]:
df2.loc[1, 'b'] = np.nan
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [110]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [111]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
1 / df1

In [ ]:
df1.rdiv(1)

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

#### Operations between DataFrame and Series

In [112]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [113]:
arr[0]

array([0., 1., 2., 3.])

In [114]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [115]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), \
                                        index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
# frame 
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [ ]:
frame

In [116]:
frame-series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2
frame + series2

In [ ]:
# broadcast over the columns
series3 = frame['d']
# frame
series3

In [ ]:
frame

In [ ]:
frame.sub(series3, axis='index') # subtraction
# (axis='index' or axis=0)

### Function Application and Mapping

In [117]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

               b         d         e
Utah   -1.911593 -0.585981 -1.665701
Ohio    1.019802  0.526988  0.516481
Texas   1.010069 -1.358022 -0.836783
Oregon  1.446228 -1.039120 -0.265401

In [121]:
# np.abs(frame)
frame

               b         d         e
Utah   -1.911593 -0.585981 -1.665701
Ohio    1.019802  0.526988  0.516481
Texas   1.010069 -1.358022 -0.836783
Oregon  1.446228 -1.039120 -0.265401

In [120]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    3.357821
d    1.885011
e    2.182183
dtype: float64

In [122]:
frame.apply(f, axis='columns')

Utah      1.325612
Ohio      0.503321
Texas     2.368091
Oregon    2.485348
dtype: float64

In [123]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

            b         d         e
min -1.911593 -1.358022 -1.665701
max  1.446228  0.526988  0.516481

In [124]:
format = lambda x: '%.2f' % x
frame.applymap(format)

            b      d      e
Utah    -1.91  -0.59  -1.67
Ohio     1.02   0.53   0.52
Texas    1.01  -1.36  -0.84
Oregon   1.45  -1.04  -0.27

In [125]:
# The reason for the name applymap is that Series has a map method for applying an element-wise function:
frame['e'].map(format)

Utah      -1.67
Ohio       0.52
Texas     -0.84
Oregon    -0.27
Name: e, dtype: object

### Sorting and Ranking

In [126]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [127]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
frame

In [128]:
frame.sort_index(axis=1)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [129]:
frame.sort_index(axis=1, ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [130]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [131]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [132]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [134]:
frame.sort_values(by ='b')

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [135]:
frame.sort_values(by=['a', 'b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

Ranking assigns ranks from one through the number of valid data points in an array.
The rank methods for Series and DataFrame are the place to look; by default rank
breaks ties by assigning each group the mean rank:

In [138]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [139]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank(method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [ ]:
# according to the order in which they’re observed in the data:
obj.rank(method='dense')
obj

In [ ]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='min')

In [ ]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

In [ ]:
frame.rank(axis='columns')

### Axis Indexes with Duplicate Labels

In [140]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [141]:
obj.index.is_unique

False

In [142]:
obj['a']
# obj['c']
# This can make your code more complicated, as the output type from indexing can
# vary based on whether a label is repeated or not.

a    0
a    1
dtype: int64

In [143]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

          0         1         2
a -0.147970  1.207995  1.066499
a  0.497339  0.076567 -1.659023
b -1.473580  1.790332  0.392897
b -0.931037 -1.210950 -1.723097

In [144]:
df.loc['b']

          0         1         2
b -1.473580  1.790332  0.392897
b -0.931037 -1.210950 -1.723097

# Summarizing and Computing Descriptive Statistics

In [145]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], \
                index=['a', 'b', 'c', 'd'], columns=['one', 'two'])  
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [146]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [147]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [148]:
df.mean(axis='columns', skipna=True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [ ]:
df.idxmax()
# return indirect statistics like the index value where the minimum or maximum values are attained

In [ ]:
df.cumsum()

In [149]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [150]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Unique Values, Value Counts, and Membership

In [151]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [ ]:
obj.value_counts()

In [ ]:
pd.value_counts(obj.values, sort=False)

In [ ]:
obj

In [ ]:
mask = obj.isin(['b', 'c'])
mask

In [ ]:
obj[mask]

Related to isin is the Index.get_indexer method, which gives you an index array
from an array of possibly non-distinct values into another array of distinct values:

In [ ]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

In [ ]:
unique_vals

In [ ]:
to_match

In [ ]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
            'Qu2': [2, 3, 1, 2, 3],
            'Qu3': [1, 5, 2, 4, 4]})
data

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result